### ISSUE TITLE
Missing information including title and files at http://ves-ebi-6f:8080/biostudies/studies/S-BSMS6

### ISSUE THREAD

**Issue by catsnow** [EBIBioStudies/ribs#3]
Vital information missing on the display, including title and files between https://www.ebi.ac.uk/biostudies/studies/S-BSMS6 and http://ves-ebi-6f:8080/biostudies/studies/S-BSMS6

**Comment by awaisathar** [comment]
S-BSMS6 has a different version of the data on the test server
