### ISSUE TITLE
jpeg thumbnails not avaliable http://ves-ebi-6f:8080/biostudies/studies/S-EPMC2559852

### ISSUE THREAD

**Issue by catsnow** [EBIBioStudies/ribs#5]
link to jpeg is unavailable subsequently the file Thumbnail can not be displayed http://ves-ebi-6f:8080/biostudies/studies/S-EPMC2559852

**Comment by awaisathar** [comment]
The path variable in the file 1471-2164-9-441-S1.jpeg does not retain complete path information 

http://wwwdev.ebi.ac.uk/biostudies/files/S-EPMC2559852/S-EPMC2559852.xml has u/... in the path but 
http://wwwdev.ebi.ac.uk/biostudies/files/S-EPMC2559852/S-EPMC2559852.json doesn't
